#ifndef INPUTSCREENSDLG_H
#define INPUTSCREENSDLG_H

//(*Headers(InputScreensDlg)
#include <wx/button.h>
#include <wx/choice.h>
#include <wx/dialog.h>
#include <wx/gauge.h>
#include <wx/grid.h>
#include <wx/notebook.h>
#include <wx/panel.h>
#include <wx/sizer.h>
#include <wx/statbmp.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
//*)
#include<string.h>
#include "include/ItemHeaders.h"
#include "include/ItemUIUtils.h"
#include "MaterialSelection.h"

class InputScreensDlg: public wxDialog
{
	public:

		InputScreensDlg(wxWindow* parent,wxWindowID id=wxID_ANY,const wxPoint& pos=wxDefaultPosition,const wxSize& size=wxDefaultSize);
		virtual ~InputScreensDlg();

		//(*Declarations(InputScreensDlg)
		wxBoxSizer* BoxSizerChoiceAddDesignLqdHead;
		wxBoxSizer* BoxSizerChoiceAppendixShellDesign;
		wxBoxSizer* BoxSizerChoiceDiaType;
		wxBoxSizer* BoxSizerChoiceMethodShellThickCalc;
		wxBoxSizer* BoxSizerChoiceTypeFixedRoof;
		wxBoxSizer* BoxSizerControlsMain;
		wxBoxSizer* BoxSizerCorrosionAllowanceBtmPlate;
		wxBoxSizer* BoxSizerCorrosionAllowanceFirstShllBtm;
		wxBoxSizer* BoxSizerCorrosionAllowanceFixedRoof;
		wxBoxSizer* BoxSizerCourseWidthFirstShellBtm;
		wxBoxSizer* BoxSizerDesignExtPressure;
		wxBoxSizer* BoxSizerDesignInternalPressure;
		wxBoxSizer* BoxSizerDesignPrdLvl;
		wxBoxSizer* BoxSizerDesignTemp;
		wxBoxSizer* BoxSizerDiaTank;
		wxBoxSizer* BoxSizerDlgButtons;
		wxBoxSizer* BoxSizerExtPressureCmbFactor;
		wxBoxSizer* BoxSizerIncWtShellNozzleOtherShellApptnces;
		wxBoxSizer* BoxSizerJointEffcncyShellVertSeams;
		wxBoxSizer* BoxSizerLiqdLvlSesDesign;
		wxBoxSizer* BoxSizerMain;
		wxBoxSizer* BoxSizerMinDesignMetalTemp;
		wxBoxSizer* BoxSizerNormalLiqdLvl;
		wxBoxSizer* BoxSizerPressureCmbFact;
		wxBoxSizer* BoxSizerSeismicDataMain;
		wxBoxSizer* BoxSizerSpecificGrvtyHydroTest;
		wxBoxSizer* BoxSizerSpecificGrvtyStrdPrd;
		wxBoxSizer* BoxSizerTankHeight;
		wxBoxSizer* BoxSizerTestWaterLvl;
		wxBoxSizer* BoxSizerVariableCtrls;
		wxBoxSizer* BoxSizerWindDataMain;
		wxBoxSizer* BoxSizerWtSpiralStairway;
		wxButton* BtnRoofData;
		wxButton* ButtonDesignShell;
		wxButton* ButtonGenReport;
		wxButton* ButtonRunShell;
		wxButton* ButtonRunStiffenerElevation;
		wxButton* ButtonRunStiffenerSize;
		wxButton* CalcFaFvBtn;
		wxButton* RunPWG;
		wxButton* btnBack;
		wxButton* btnCancel;
		wxButton* btnOk;
		wxButton* windDataRunButton;
		wxChoice* CmbRoundUpTo;
		wxChoice* cmbChoiceAddDesignLqdHead;
		wxChoice* cmbChoiceAppendixShellDesign;
		wxChoice* cmbChoiceCodeWindLoad;
		wxChoice* cmbChoiceDiaType;
		wxChoice* cmbChoiceExposureCatgory;
		wxChoice* cmbChoiceGovByASCERules;
		wxChoice* cmbChoiceImportanceFactor;
		wxChoice* cmbChoiceMethodShellThickCalc;
		wxChoice* cmbChoiceSeismicDesignChoice;
		wxChoice* cmbChoiceSeismicSiteClass;
		wxChoice* cmbChoiceSeismicUserGrp;
		wxChoice* cmbChoiceTypeFixedRoof;
		wxChoice* cmbChoiceUBCZoneNo;
		wxChoice* cmbChoiceVertSeismicEffect;
		wxChoice* cmbFrangible;
		wxChoice* cmbJointEff;
		wxChoice* cmbJointEffcncyShellVertSeams;
		wxChoice* cmbOptionStfr;
		wxChoice* cmbReqAnchorage;
		wxChoice* cmbReqAnnular;
		wxChoice* cmbRoofType;
		wxChoice* cmbTopWGAsWalkway;
		wxChoice* cmbTypeCR;
		wxChoice* cmbTypeCRAD;
		wxChoice* cmbTypeFloatingRoof;
		wxChoice* cmblDesignTopWGTankDia;
		wxChoice* cmblSizeTopAngle;
		wxGauge* Gauge1;
		wxGrid* GridStiffenerElevation;
		wxGrid* GridStiffenerElevationLabel;
		wxGrid* GridStiffenerSize;
		wxGrid* GridStiffenerSizeLabel1;
		wxGrid* Gridpwg;
		wxGrid* gridShellDesign;
		wxGrid* gridShellDesignLabel;
		wxNotebook* NotebookInputScreen_1;
		wxPanel* Panel1;
		wxPanel* pnlAccelBaseSiteCoeff;
		wxPanel* pnlBottomPlateAnchorDesign;
		wxPanel* pnlCodeWindLoad;
		wxPanel* pnlCoeffAdjust;
		wxPanel* pnlDesignWindVel;
		wxPanel* pnlDirectionFactor;
		wxPanel* pnlDummy;
		wxPanel* pnlDummySeismic;
		wxPanel* pnlExposureCatgory;
		wxPanel* pnlGovByASCERules;
		wxPanel* pnlGrpASCE;
		wxPanel* pnlGrpPeakGrndAccel;
		wxPanel* pnlGrpUBC;
		wxPanel* pnlGustDesignWindSpeed;
		wxPanel* pnlGustFactor;
		wxPanel* pnlImportanceFactor;
		wxPanel* pnlInputScreen_1;
		wxPanel* pnlMainPrimaryWindGirder;
		wxPanel* pnlRoofData;
		wxPanel* pnlRoofToShell;
		wxPanel* pnlSD1QFvS1;
		wxPanel* pnlSDSQFaSs;
		wxPanel* pnlSeismicData;
		wxPanel* pnlSeismicDesignChoice;
		wxPanel* pnlSeismicImportanceFactor;
		wxPanel* pnlSeismicScaleFactor;
		wxPanel* pnlSeismicSiteClass;
		wxPanel* pnlSeismicUserGrp;
		wxPanel* pnlShlDesMain;
		wxPanel* pnlSpectralAccelTimePeriod0;
		wxPanel* pnlStiffenerElevation;
		wxPanel* pnlTopographicFactor;
		wxPanel* pnlTransitionLongGrnd;
		wxPanel* pnlVelBasedSiteCoeff;
		wxPanel* pnlVelPressureExpCoeff;
		wxPanel* pnlVertSeismicEffect;
		wxPanel* pnlWindData;
		wxStaticBitmap* StaticBitmap1;
		wxStaticText* StaticText1;
		wxStaticText* StaticText2;
		wxStaticText* StaticText3;
		wxStaticText* StaticText4;
		wxStaticText* StaticText5;
		wxStaticText* StaticText6;
		wxStaticText* StaticTextSlopeSlash;
		wxStaticText* StaticTextad;
		wxStaticText* StaticTextaval;
		wxStaticText* StaticTextlblCrossInt;
		wxStaticText* StaticTextreq;
		wxStaticText* StaticTextud;
		wxStaticText* lblASCESpectralAccelOneSec;
		wxStaticText* lblASCESpectralAccelShort;
		wxStaticText* lblAccelBaseSiteCoeff;
		wxStaticText* lblAddDesignLqdHead;
		wxStaticText* lblAnchorChairHeight;
		wxStaticText* lblAppendixShellDesign;
		wxStaticText* lblAvgVerticalPlateWidth;
		wxStaticText* lblBalSL;
		wxStaticText* lblBoltEccentricity;
		wxStaticText* lblCodeWindLoad;
		wxStaticText* lblCoeffAdjust;
		wxStaticText* lblCorrWeight;
		wxStaticText* lblCorrosionAllowance;
		wxStaticText* lblCorrosionAllowanceBtmPlate;
		wxStaticText* lblCorrosionAllowanceFirstShllBtm;
		wxStaticText* lblCorrosionAllowanceFixedRoof;
		wxStaticText* lblCourseWidthFirstShellBtm;
		wxStaticText* lblCrossExt;
		wxStaticText* lblDesignExtPressure;
		wxStaticText* lblDesignInternalPressure;
		wxStaticText* lblDesignPrdLvl;
		wxStaticText* lblDesignTemp;
		wxStaticText* lblDesignTopWGTankDia;
		wxStaticText* lblDesignWindVel;
		wxStaticText* lblDiaTank;
		wxStaticText* lblDiaType;
		wxStaticText* lblDirectionFactor;
		wxStaticText* lblDomeRadius;
		wxStaticText* lblExposureCatgory;
		wxStaticText* lblExtPressureCmbFactor;
		wxStaticText* lblFrangible;
		wxStaticText* lblGovByASCERules;
		wxStaticText* lblGustDesignWindSpeed;
		wxStaticText* lblGustFactor;
		wxStaticText* lblHMaxPressure;
		wxStaticText* lblHMaxWind;
		wxStaticText* lblHTankHeight;
		wxStaticText* lblHeightTransShell;
		wxStaticText* lblImportanceFactor;
		wxStaticText* lblIncWtShellNozzleOtherShellApptnces;
		wxStaticText* lblJEff;
		wxStaticText* lblJointEffcncyShellVertSeams;
		wxStaticText* lblLiqdLvlSesDesign;
		wxStaticText* lblLiveLoad;
		wxStaticText* lblMIExt;
		wxStaticText* lblMOIRqd;
		wxStaticText* lblMaterialCR;
		wxStaticText* lblMaterialRoof;
		wxStaticText* lblMaxSpace;
		wxStaticText* lblMaxSpacePeri;
		wxStaticText* lblMethodShellThickCalc;
		wxStaticText* lblMinDesignMetalTemp;
		wxStaticText* lblMinWidthTopWGAsWalkway;
		wxStaticText* lblNominalBoltDia;
		wxStaticText* lblNormalLiqdLvl;
		wxStaticText* lblNumAnchorBolts;
		wxStaticText* lblNumStiff;
		wxStaticText* lblNumStiffMax;
		wxStaticText* lblPGASpectralAccelOneSec;
		wxStaticText* lblPGASpectralAccelShort;
		wxStaticText* lblPadThickness;
		wxStaticText* lblPeakGroundAccel;
		wxStaticText* lblPercWeight;
		wxStaticText* lblPressureCmbFact;
		wxStaticText* lblProj;
		wxStaticText* lblProjAD;
		wxStaticText* lblRRoof;
		wxStaticText* lblReqAnchorage;
		wxStaticText* lblReqAnnular;
		wxStaticText* lblRoofTypeAdopted;
		wxStaticText* lblRoofTypeUser;
		wxStaticText* lblSD1QFvS1;
		wxStaticText* lblSDSQFaSs;
		wxStaticText* lblSectionModRqd;
		wxStaticText* lblSeismicDesignChoice;
		wxStaticText* lblSeismicImportanceFactor;
		wxStaticText* lblSeismicScaleFactor;
		wxStaticText* lblSeismicSiteClass;
		wxStaticText* lblSeismicUserGrp;
		wxStaticText* lblSizeTopAngle;
		wxStaticText* lblSlopeRoof;
		wxStaticText* lblSpaceTopWGTopTank;
		wxStaticText* lblSpacingBetweenGussets;
		wxStaticText* lblSpecificGrvtyHydroTest;
		wxStaticText* lblSpecificGrvtyStrdPrd;
		wxStaticText* lblSpectralAccelTimePeriod0;
		wxStaticText* lblTCR_AD;
		wxStaticText* lblTHickness;
		wxStaticText* lblT_uniform;
		wxStaticText* lblTestWaterLvl;
		wxStaticText* lblThickness;
		wxStaticText* lblThicknessAD;
		wxStaticText* lblThicknessAnnularPlate;
		wxStaticText* lblThicknessBottomPlate;
		wxStaticText* lblTopPlateLengthRadial;
		wxStaticText* lblTopPlateLengthShell;
		wxStaticText* lblTopPlateThickness;
		wxStaticText* lblTopWGAsWalkway;
		wxStaticText* lblTopographicFactor;
		wxStaticText* lblTransitionLongGrnd;
		wxStaticText* lblTypeCR;
		wxStaticText* lblTypeFR;
		wxStaticText* lblTypeFixedRoof;
		wxStaticText* lblUBCPeakGrndAccel;
		wxStaticText* lblUBCSpectralAccelOneSec;
		wxStaticText* lblUBCSpectralAccelShort;
		wxStaticText* lblUBCZoneNo;
		wxStaticText* lblUnBalSL;
		wxStaticText* lblUser1;
		wxStaticText* lblUser1AD;
		wxStaticText* lblUser2;
		wxStaticText* lblUser2AD;
		wxStaticText* lblUser3;
		wxStaticText* lblUser3AD;
		wxStaticText* lblUser4;
		wxStaticText* lblUser4AD;
		wxStaticText* lblVelBasedSiteCoeff;
		wxStaticText* lblVelPressureExpCoeff;
		wxStaticText* lblVertSeismicEffect;
		wxStaticText* lblVerticalPlateThickness;
		wxStaticText* lblWeightFR;
		wxStaticText* lblWeightGeodesicRoof;
		wxStaticText* lblWidth;
		wxStaticText* lblWidthAD;
		wxStaticText* lblWidthAnnularPlate;
		wxStaticText* lblWtNozzle;
		wxStaticText* lblWtSpiralStairway;
		wxStaticText* lblYeildStrengthBoltMaterial;
		wxTextCtrl* TextHMaxPressure;
		wxTextCtrl* TextHMaxWind;
		wxTextCtrl* TextHeightTransShell;
		wxTextCtrl* TextMOIRqd;
		wxTextCtrl* TextNumStiff;
		wxTextCtrl* TextNumStiffMax;
		wxTextCtrl* TextSectionModRqd;
		wxTextCtrl* TextT_uniform;
		wxTextCtrl* txtASCESpectralAccelOneSec;
		wxTextCtrl* txtASCESpectralAccelShort;
		wxTextCtrl* txtAccelBaseSiteCoeff;
		wxTextCtrl* txtAnchorChairHeight;
		wxTextCtrl* txtAvgVerticalPlateWidth;
		wxTextCtrl* txtBalancedSL;
		wxTextCtrl* txtBoltEccentricity;
		wxTextCtrl* txtCRMaterial0;
		wxTextCtrl* txtCRMaterial1;
		wxTextCtrl* txtCRMaterial2;
		wxTextCtrl* txtCRSize1;
		wxTextCtrl* txtCRSize1AD;
		wxTextCtrl* txtCRSize2;
		wxTextCtrl* txtCRSize2AD;
		wxTextCtrl* txtCoeffAdjust;
		wxTextCtrl* txtCorrWeight;
		wxTextCtrl* txtCorrosionAllowance;
		wxTextCtrl* txtCorrosionAllowanceBtmPlate;
		wxTextCtrl* txtCorrosionAllowanceFirstShllBtm;
		wxTextCtrl* txtCorrosionAllowanceFixedRoof;
		wxTextCtrl* txtCourseWidthFirstShellBtm;
		wxTextCtrl* txtCrossSecExternalPressureAvail;
		wxTextCtrl* txtCrossSecExternalPressureReq;
		wxTextCtrl* txtCrossSecInternalPressureAvail;
		wxTextCtrl* txtCrossSecInternalPressureReq;
		wxTextCtrl* txtDesignExtPressure;
		wxTextCtrl* txtDesignInternalPressure;
		wxTextCtrl* txtDesignPrdLvl;
		wxTextCtrl* txtDesignTemp;
		wxTextCtrl* txtDesignWindVel;
		wxTextCtrl* txtDiaTank;
		wxTextCtrl* txtDirectionFactor;
		wxTextCtrl* txtDomeRadius;
		wxTextCtrl* txtExtPressureCmbFactor;
		wxTextCtrl* txtGustDesignWindSpeed;
		wxTextCtrl* txtGustFactor;
		wxTextCtrl* txtIncWtShellNozzleOtherShellApptnces;
		wxTextCtrl* txtLBar;
		wxTextCtrl* txtLBarAD;
		wxTextCtrl* txtLiqdLvlSesDesign;
		wxTextCtrl* txtLiveLoad;
		wxTextCtrl* txtMIExternalPressureAvail;
		wxTextCtrl* txtMIExternalPressureReq;
		wxTextCtrl* txtMaterialRoof;
		wxTextCtrl* txtMaxSpace1;
		wxTextCtrl* txtMaxSpace2;
		wxTextCtrl* txtMinDesignMetalTemp;
		wxTextCtrl* txtMinWidthTopWGAsWalkway;
		wxTextCtrl* txtNominalBoltDia;
		wxTextCtrl* txtNormalLiqdLvl;
		wxTextCtrl* txtNumAnchorBolts;
		wxTextCtrl* txtPGASpectralAccelOneSec;
		wxTextCtrl* txtPGASpectralAccelShort;
		wxTextCtrl* txtPadThickness;
		wxTextCtrl* txtPeakGroundAccel;
		wxTextCtrl* txtPercWeight;
		wxTextCtrl* txtPressureCmbFact;
		wxTextCtrl* txtRRoof;
		wxTextCtrl* txtRequiredThickness;
		wxTextCtrl* txtRoofTypeAdopted;
		wxTextCtrl* txtSD1QFvS1;
		wxTextCtrl* txtSDSQFaSs;
		wxTextCtrl* txtSeismicImportanceFactor;
		wxTextCtrl* txtSeismicScaleFactor;
		wxTextCtrl* txtSlopeDen;
		wxTextCtrl* txtSlopeNum;
		wxTextCtrl* txtSpaceTopWGTopTank;
		wxTextCtrl* txtSpacingBetweenGussets;
		wxTextCtrl* txtSpecificGrvtyHydroTest;
		wxTextCtrl* txtSpecificGrvtyStrdPrd;
		wxTextCtrl* txtSpectralAccelTimePeriod0;
		wxTextCtrl* txtTBar;
		wxTextCtrl* txtTBarAD;
		wxTextCtrl* txtTShell;
		wxTextCtrl* txtTShellAD;
		wxTextCtrl* txtTankHeight;
		wxTextCtrl* txtTestWaterLvl;
		wxTextCtrl* txtThicknessAnnularPlate;
		wxTextCtrl* txtThicknessBottomPlate;
		wxTextCtrl* txtTopPlateLengthRadial;
		wxTextCtrl* txtTopPlateLengthShell;
		wxTextCtrl* txtTopPlateThickness;
		wxTextCtrl* txtTopographicFactor;
		wxTextCtrl* txtTransitionLongGrnd;
		wxTextCtrl* txtUBCPeakGrndAccel;
		wxTextCtrl* txtUBCSpectralAccelOneSec;
		wxTextCtrl* txtUBCSpectralAccelShort;
		wxTextCtrl* txtUnBalancedSL;
		wxTextCtrl* txtVelBasedSiteCoeff;
		wxTextCtrl* txtVelPressureExpCoeff;
		wxTextCtrl* txtVerticalPlateThickness;
		wxTextCtrl* txtWBar;
		wxTextCtrl* txtWBarAD;
		wxTextCtrl* txtWShell;
		wxTextCtrl* txtWShellAD;
		wxTextCtrl* txtWeightFloatingRoof;
		wxTextCtrl* txtWeightNozzle;
		wxTextCtrl* txtWidthAnnularPlate;
		wxTextCtrl* txtWtGeodesicRoof;
		wxTextCtrl* txtWtSpiralStairway;
		wxTextCtrl* txtYeildStrengthBoltMaterial;
		//*)

	protected:

		//(*Identifiers(InputScreensDlg)
		static const long ID_STATICTEXT1;
		static const long ID_TEXTCTRL1;
		static const long ID_STATICTEXT2;
		static const long ID_CHOICE1;
		static const long ID_STATICTEXT3;
		static const long ID_TEXTCTRL3;
		static const long ID_STATICTEXT4;
		static const long ID_TEXTCTRL4;
		static const long ID_STATICTEXT5;
		static const long ID_TEXTCTRL5;
		static const long ID_STATICTEXT6;
		static const long ID_TEXTCTRL6;
		static const long ID_STATICTEXT7;
		static const long ID_TEXTCTRL7;
		static const long ID_STATICTEXT8;
		static const long ID_TEXTCTRL8;
		static const long ID_STATICTEXT9;
		static const long ID_TEXTCTRL9;
		static const long ID_STATICTEXT10;
		static const long ID_TEXTCTRL10;
		static const long ID_STATICTEXT11;
		static const long ID_TEXTCTRL11;
		static const long ID_STATICTEXT12;
		static const long ID_TEXTCTRL12;
		static const long ID_STATICTEXT13;
		static const long ID_TEXTCTRL13;
		static const long ID_STATICTEXT14;
		static const long ID_CHOICE2;
		static const long ID_STATICTEXT15;
		static const long ID_TEXTCTRL15;
		static const long ID_STATICTEXT16;
		static const long ID_TEXTCTRL16;
		static const long ID_STATICTEXT17;
		static const long ID_CHOICE3;
		static const long ID_STATICTEXT18;
		static const long ID_TEXTCTRL18;
		static const long ID_STATICTEXT19;
		static const long ID_TEXTCTRL19;
		static const long ID_STATICTEXT20;
		static const long ID_CHOICE21;
		static const long ID_STATICTEXT21;
		static const long ID_CHOICE4;
		static const long ID_STATICTEXT22;
		static const long ID_TEXTCTRL22;
		static const long ID_STATICTEXT23;
		static const long ID_CHOICE5;
		static const long ID_STATICTEXT24;
		static const long ID_TEXTCTRL24;
		static const long ID_STATICTEXT25;
		static const long ID_TEXTCTRL25;
		static const long ID_STATICTEXT26;
		static const long ID_TEXTCTRL26;
		static const long ID_STATICTEXT64;
		static const long ID_CHOICE18;
		static const long ID_STATICTEXT65;
		static const long ID_CHOICE19;
		static const long ID_PANEL1;
		static const long ID_STATICTEXT27;
		static const long ID_CHOICE6;
		static const long ID_PANEL3;
		static const long ID_PANEL12;
		static const long ID_STATICTEXT29;
		static const long ID_TEXTCTRL17;
		static const long ID_PANEL5;
		static const long ID_STATICTEXT28;
		static const long ID_CHOICE7;
		static const long ID_PANEL6;
		static const long ID_STATICTEXT30;
		static const long ID_TEXTCTRL2;
		static const long ID_PANEL4;
		static const long ID_STATICTEXT31;
		static const long ID_TEXTCTRL14;
		static const long ID_PANEL7;
		static const long ID_STATICTEXT32;
		static const long ID_TEXTCTRL21;
		static const long ID_PANEL8;
		static const long ID_STATICTEXT33;
		static const long ID_CHOICE8;
		static const long ID_PANEL9;
		static const long ID_STATICTEXT34;
		static const long ID_TEXTCTRL23;
		static const long ID_PANEL10;
		static const long ID_STATICTEXT35;
		static const long ID_TEXTCTRL27;
		static const long ID_PANEL11;
		static const long ID_BUTTON1;
		static const long ID_PANEL2;
		static const long ID_STATICTEXT36;
		static const long ID_CHOICE9;
		static const long ID_PANEL14;
		static const long ID_PANEL15;
		static const long ID_STATICTEXT37;
		static const long ID_TEXTCTRL28;
		static const long ID_STATICTEXT38;
		static const long ID_TEXTCTRL29;
		static const long ID_STATICTEXT39;
		static const long ID_TEXTCTRL30;
		static const long ID_PANEL16;
		static const long ID_STATICTEXT40;
		static const long ID_CHOICE10;
		static const long ID_STATICTEXT41;
		static const long ID_TEXTCTRL31;
		static const long ID_STATICTEXT42;
		static const long ID_TEXTCTRL32;
		static const long ID_STATICTEXT43;
		static const long ID_TEXTCTRL33;
		static const long ID_PANEL17;
		static const long ID_STATICTEXT44;
		static const long ID_TEXTCTRL34;
		static const long ID_STATICTEXT45;
		static const long ID_TEXTCTRL35;
		static const long ID_PANEL18;
		static const long ID_BUTTON5;
		static const long ID_STATICTEXT46;
		static const long ID_TEXTCTRL36;
		static const long ID_PANEL20;
		static const long ID_STATICTEXT47;
		static const long ID_CHOICE11;
		static const long ID_PANEL21;
		static const long ID_STATICTEXT48;
		static const long ID_TEXTCTRL38;
		static const long ID_PANEL22;
		static const long ID_STATICTEXT49;
		static const long ID_CHOICE12;
		static const long ID_PANEL23;
		static const long ID_STATICTEXT50;
		static const long ID_TEXTCTRL40;
		static const long ID_PANEL24;
		static const long ID_STATICTEXT51;
		static const long ID_CHOICE13;
		static const long ID_PANEL25;
		static const long ID_STATICTEXT52;
		static const long ID_TEXTCTRL42;
		static const long ID_PANEL26;
		static const long ID_STATICTEXT53;
		static const long ID_TEXTCTRL43;
		static const long ID_PANEL27;
		static const long ID_STATICTEXT54;
		static const long ID_TEXTCTRL44;
		static const long ID_PANEL28;
		static const long ID_STATICTEXT55;
		static const long ID_TEXTCTRL45;
		static const long ID_PANEL29;
		static const long ID_STATICTEXT56;
		static const long ID_TEXTCTRL46;
		static const long ID_PANEL30;
		static const long ID_STATICTEXT57;
		static const long ID_TEXTCTRL47;
		static const long ID_PANEL31;
		static const long ID_STATICTEXT58;
		static const long ID_CHOICE14;
		static const long ID_PANEL19;
		static const long ID_PANEL13;
		static const long ID_GRID1;
		static const long ID_BUTTON2;
		static const long ID_BUTTON3;
		static const long ID_GRID44;
		static const long ID_STATICTEXT91;
		static const long ID_PANEL32;
		static const long ID_STATICTEXT59;
		static const long ID_STATICTEXT60;
		static const long ID_STATICTEXT61;
		static const long ID_STATICTEXT62;
		static const long ID_STATICTEXT63;
		static const long ID_CHOICE15;
		static const long ID_TEXTCTRL37;
		static const long ID_CHOICE16;
		static const long ID_TEXTCTRL39;
		static const long ID_CHOICE17;
		static const long ID_GRID6;
		static const long ID_BUTTON6;
		static const long ID_STATICTEXT66;
		static const long ID_TEXTCTRL41;
		static const long ID_STATICTEXT67;
		static const long ID_TEXTCTRL48;
		static const long ID_PANEL33;
		static const long ID_STATICTEXTlblHeightTransShell;
		static const long ID_STATICTEXTlblT_uniform;
		static const long ID_STATICTEXTlblHMaxWind;
		static const long ID_STATICTEXT92;
		static const long ID_STATICTEXTlblNumStiff;
		static const long ID_STATICTEXTlblNumStiffMax;
		static const long ID_TEXTCTRLTextHeightTransShell;
		static const long ID_TEXTCTRLTextT_uniform;
		static const long ID_TEXTCTRLTextHMaxWind;
		static const long ID_TEXTCTRLTextHMaxPressure;
		static const long ID_TEXTCTRLTextNumStiff;
		static const long ID_TEXTCTRLTextNumStiffMax;
		static const long ID_GRID2;
		static const long ID_STATICTEXT89;
		static const long ID_STATICTEXT90;
		static const long ID_GRID3;
		static const long ID_BUTTON4;
		static const long ID_PANEL35;
		static const long ID_GRID4;
		static const long ID_GRID5;
		static const long ID_BUTTON7;
		static const long ID_PANEL37;
		static const long ID_STATICTEXTlblRoofTypeUser;
		static const long ID_CHOICEroofTypeUser;
		static const long ID_STATICTEXTlblRRoof;
		static const long ID_STATICTEXTlblFrangible;
		static const long ID_STATICTEXTlblLiveLoad;
		static const long ID_STATICTEXTlblBalSL;
		static const long ID_STATICTEXTlblUnBalSL;
		static const long ID_STATICTEXTtypeFR;
		static const long ID_STATICTEXTlblMaterialRoof;
		static const long ID_STATICTEXTlblJEff;
		static const long ID_STATICTEXTlblThickness;
		static const long ID_TEXTCTRL61;
		static const long ID_TEXTCTRLtxtMaxSpace1;
		static const long ID_TEXTCTRLtxtMaxSpace2;
		static const long ID_STATICTEXTlblWeightNozzle;
		static const long ID_STATICTEXTlblWeightFR;
		static const long ID_STATICTEXTlblSlopeRoof;
		static const long ID_STATICTEXTlblDomeRadius;
		static const long ID_STATICTEXTlblMaxSpace;
		static const long ID_STATICTEXTlblMaxSPacePeri;
		static const long ID_TEXTCTRLtxtRRoof;
		static const long ID_STATICTEXTlblRoofTypeAdopted;
		static const long ID_TEXTCTRLtxtRoofTypeAdopted;
		static const long ID_CHOICEFrangible;
		static const long ID_TEXTCTRLtxtLiveLoad;
		static const long ID_TEXTCTRLtxtBalancedSL;
		static const long ID_TEXTCTRLtxtUnBalancedSL;
		static const long ID_TEXTCTRLtxtDomeRadius;
		static const long ID_STATICTEXTwtGeodesicRoof;
		static const long ID_TEXTCTRLWtGeodesicRoof;
		static const long ID_TEXTCTRLtxtMaterialRoof;
		static const long ID_TEXTCTRLtxtWeightNozzle;
		static const long ID_CHOICEFR;
		static const long ID_TEXTCTRLtxtWeightFloatingRoof;
		static const long ID_CHOICE20;
		static const long ID_STATICTEXT68;
		static const long ID_TEXTCTRL20;
		static const long ID_TEXTCTRL49;
		static const long ID_STATICTEXT69;
		static const long ID_STATICTEXT70;
		static const long ID_GAUGE1;
		static const long ID_TEXTCTRL52;
		static const long ID_STATICTEXT72;
		static const long ID_TEXTCTRL50;
		static const long ID_BUTTON9;
		static const long ID_PANEL;
		static const long ID_CHOICEcmbTypeCR;
		static const long ID_STATICBITMAP;
		static const long ID_STATICTEXTud;
		static const long ID_STATICTEXT88req;
		static const long ID_STATICTEXTaval;
		static const long ID_TEXTCTRLtxtCrossSecInternalPressureReq;
		static const long ID_TEXTCTRLtxtCrossSecExternalPressureReq;
		static const long ID_TEXTCTRLtxtMIExternalPressureReq;
		static const long ID_TEXTCTRLtxtCrossSecInternalPressureAvail;
		static const long ID_TEXTCTRLtxtCrossSecExternalPressureAvail;
		static const long ID_TEXTCTRLtxtMIExternalPressureAvail;
		static const long ID_STATICTEXTlblCrossInt;
		static const long ID_STATICTEXTlblCrossExt;
		static const long ID_STATICTEXTlblMIExt;
		static const long ID_STATICTEXTlblTypeCR;
		static const long ID_STATICTEXTlblThick;
		static const long ID_STATICTEXTlblWidth;
		static const long ID_STATICTEXTlblProj;
		static const long ID_TEXTCTRLtxtCRSize1;
		static const long ID_TEXTCTRLtxtCRSize2;
		static const long ID_TEXTCTRLtxtTbar;
		static const long ID_TEXTCTRLtxtWBar;
		static const long ID_TEXTCTRLtxtLBar;
		static const long ID_TEXTCTRLtxtTShell;
		static const long ID_TEXTCTRLtxtWShell;
		static const long ID_STATICTEXTlblUser1;
		static const long ID_STATICTEXTlblUser2;
		static const long ID_STATICTEXTlblUser3;
		static const long ID_STATICTEXTlblUser4;
		static const long ID_STATICTEXTlblMaterialCR;
		static const long ID_TEXTCTRLtxtCRMaterial0;
		static const long ID_TEXTCTRLtxtCRMaterial2;
		static const long ID_TEXTCTRLtxtCRMaterial1;
		static const long ID_STATICTEXT88;
		static const long ID_CHOICEcmbTypeCRAD;
		static const long ID_TCRAD;
		static const long ID_STATICTEXTlblThickNessAD;
		static const long ID_STATICTEXTlblWidthAD;
		static const long ID_STATICTEXTlblProjAD;
		static const long ID_STATICTEXTlblAD1;
		static const long ID_STATICTEXTlblAD2;
		static const long ID_STATICTEXTlblAD3;
		static const long ID_STATICTEXTlblAD4;
		static const long ID_TEXTCTRLtxtTypeCR1AD;
		static const long ID_TEXTCTRLtxtTypeCR2AD;
		static const long ID_TEXTCTRLtxtTBarAD;
		static const long ID_TEXTCTRLtxtWBarAD;
		static const long ID_TEXTCTRLtxtLBarAD;
		static const long ID_TEXTCTRLtxtTShellAD;
		static const long ID_TEXTCTRLWShell;
		static const long ID_PANEL34;
		static const long ID_STATICTEXTlblThicknessBottomPlate;
		static const long ID_STATICTEXTlblReqAnnular;
		static const long ID_STATICTEXTlblThicknessAnnularPlate;
		static const long ID_STATICTEXTlblWidthAnnularPlate;
		static const long ID_STATICTEXTlblReqAnchorage;
		static const long ID_STATICTEXTlblNumAnchorBolts;
		static const long ID_STATICTEXTlblNominalBoltDia;
		static const long ID_STATICTEXTlblCorrosionAllowance;
		static const long ID_STATICTEXTlblYeildStrengthBoltMaterial;
		static const long ID_TEXTCTRLtxtThicknessBottomPlate;
		static const long ID_CHOICEcmbReqAnnular;
		static const long ID_TEXTCTRLtxtThicknessAnnularPlate;
		static const long ID_TEXTCTRLtxtWidthAnnularPlate;
		static const long ID_CHOICEcmbReqAnchorage;
		static const long ID_TEXTCTRLtxtNumAnchorBolts;
		static const long ID_TEXTCTRLtxtNominalBoltDia;
		static const long ID_TEXTCTRLtxtCorrosionAllowance;
		static const long ID_TEXTCTRLtxtYeildStrengthBoltMaterial;
		static const long ID_STATICTEXTlblPadThickness;
		static const long ID_STATICTEXTlblSpacingBetweenGussets;
		static const long ID_STATICTEXTlblTopPlateLengthShell;
		static const long ID_STATICTEXTlblTopPlateLengthRadial;
		static const long ID_STATICTEXTlblTopPlateThickness;
		static const long ID_STATICTEXTlblBoltEccentricity;
		static const long ID_STATICTEXTlblAnchorChairHeight;
		static const long ID_STATICTEXTlblVerticalPlateThickness;
		static const long ID_STATICTEXTlblAvgVerticalPlateWidth;
		static const long ID_TEXTCTRLtxtPadThickness;
		static const long ID_TEXTCTRLtxtSpacingBetweenGussets;
		static const long ID_TEXTCTRLtxtTopPlateLengthShell;
		static const long ID_TEXTCTRLtxtTopPlateLengthRadial;
		static const long ID_TEXTCTRLtxtTopPlateThickness;
		static const long ID_TEXTCTRLtxtBoltEccentricity;
		static const long ID_TEXTCTRLtxtAnchorChairHeight;
		static const long ID_TEXTCTRLtxtVerticalPlateThickness;
		static const long ID_TEXTCTRLtxtAvgVerticalPlateWidth;
		static const long ID_PANEL36;
		static const long ID_NOTEBOOK1;
		static const long ID_BUTTON10;
		static const long ID_BUTTON8;
		//*)

	private:

		//(*Handlers(InputScreensDlg)
		void OnNotebookInputScreen_1PageChanged(wxNotebookEvent& event);
		void OnbtnOkClick(wxCommandEvent& event);
		void OncmbChoiceDiaTypeSelect(wxCommandEvent& event);
		void OncmbChoiceAddDesignLqdHeadSelect(wxCommandEvent& event);
		void OncmbChoiceAppendixShellDesignSelect(wxCommandEvent& event);
		void OncmbChoiceMethodShellThickCalcSelect(wxCommandEvent& event);
		void OncmbChoiceTypeFixedRoofSelect(wxCommandEvent& event);
		void OnraghavTBKillFocus(wxFocusEvent& event);
		void OncmbChoiceCodeWindLoadSelect(wxCommandEvent& event);
		void OncmbChoiceImportanceFactorSelect(wxCommandEvent& event);
		void OncmbChoiceExposureCatgorySelect(wxCommandEvent& event);
		void OncmbChoiceGovByASCERulesSelect(wxCommandEvent& event);
		void OncmbChoiceSeismicUserGrpSelect(wxCommandEvent& event);
		void OncmbChoiceVertSeismicEffectSelect(wxCommandEvent& event);
		void OncmbChoiceSeismicDesignChoiceSelect(wxCommandEvent& event);
		void OncmbChoiceUBCZoneNoSelect(wxCommandEvent& event);
		void OncmbChoiceSeismicSiteClassSelect(wxCommandEvent& event);
		void OnGrid1CellLeftClick(wxGridEvent& event);
		void OncmbTopWGAsWalkwaySelect(wxCommandEvent& event);
		void OncmblDesignTopWGTankDiaSelect(wxCommandEvent& event);
		void OnNotebookInputScreen_1PageChanging(wxNotebookEvent& event);
		void OnpnlDummySeismicPaint(wxPaintEvent& event);
		void OntxtDiaTankText(wxCommandEvent& event);
		void OnraghavTBText(wxCommandEvent& event);
		void OncmbFrangibleSelect(wxCommandEvent& event);
		void OncmbTypeFloatingRoofSelect(wxCommandEvent& event);
		void OnPanel1Paint(wxPaintEvent& event);
		void OncmbFrangibleSelect1(wxCommandEvent& event);
		void OncmbTypeFloatingRoofSelect1(wxCommandEvent& event);
		void OncmbFrangibleSelect2(wxCommandEvent& event);
		void OnTextCtrl1Text(wxCommandEvent& event);
		void OntxtMaterialRoofLeftClick(wxCommandEvent& event);
		void OntxtMaterialRoofKeyDown(wxCommandEvent& event);
		void OnpnlRoofDataPaint(wxPaintEvent& event);
		void OnraghavButtonClick(wxCommandEvent& event);
		void OncmbTypeCRSelect(wxCommandEvent& event);
		void OntxtCrossSecInternalPressureAvailText(wxCommandEvent& event);
		void OntxtCRMaterial0Text(wxCommandEvent& event);
		void OntxtCRMaterial2Text(wxCommandEvent& event);
		void OncmblSizeTopAngleSelect(wxCommandEvent& event);
		void OnButton1Click(wxCommandEvent& event);
		void OnwindDataRunButtonClick(wxCommandEvent& event);
		void OnButtonRunShellClick(wxCommandEvent& event);
		void OnButtonDesignShellClick(wxCommandEvent& event);
		void OnGridStiffenerElevationCellLeftClick(wxGridEvent& event);
		void OnGridStiffenerSizeCellLeftClick(wxGridEvent& event);
		void OnCalcFaFvBtnClick(wxCommandEvent& event);
		void OnPanel1Paint1(wxPaintEvent& event);
		void OntxtSpaceTopWGTopTankText(wxCommandEvent& event);
		void OnTextCtrl1Text1(wxCommandEvent& event);
		void OncmbTopWGAsWalkwaySelect1(wxCommandEvent& event);
		void OnGrid1CellLeftClick1(wxGridEvent& event);
		void OnRunPWGClick(wxCommandEvent& event);
		void OnRunPWGClick1(wxCommandEvent& event);
		void OngridShellDesignLabelCellLeftClick(wxGridEvent& event);
		void OnButtonRunStiffenerElevationClick(wxCommandEvent& event);
		void OnButtonRunStiffenerSizeClick(wxCommandEvent& event);
		void OnButtonDesignClick(wxCommandEvent& event);
		void OnCmbRoundUpToSelect(wxCommandEvent& event);
		void OncmbOptionStfrSelect(wxCommandEvent& event);
		void OnGridtestCellLeftClick(wxGridEvent& event);
		void OnComboBoxSelected(wxCommandEvent& event);
		void OnGridStiffenerSizeCellChanged(wxGridEvent& event);
		void OnGrid1CellChanged(wxGridEvent& event);
		void OnChoice1Select(wxCommandEvent& event);
		void OnButtonGenReportClick(wxCommandEvent& event);
		void OncmbJointEffcncyShellVertSeamsSelect(wxCommandEvent& event);
		void OntxtSlopeNumText(wxCommandEvent& event);
		void OntxtSlopeDenText(wxCommandEvent& event);
		void OnButton1Click1(wxCommandEvent& event);
		void OnButton1Click2(wxCommandEvent& event);
		void OnbtnCancelClick(wxCommandEvent& event);
		void OnButton1Click3(wxCommandEvent& event);
		void OnbtnBackClick(wxCommandEvent& event);
		//*)

		DECLARE_EVENT_TABLE()

		void OntxtDiaTankKillFocus(wxFocusEvent& event);
		void OntxtTankHeightKillFocus(wxFocusEvent& event);
		void OntxtDesignPrdLvlKillFocus(wxFocusEvent& event);
		void OntxtTestWaterLvlKillFocus(wxFocusEvent& event);
		void OntxtNormalLiqdLvlKillFocus(wxFocusEvent& event);
		void OntxtLiqdLvlSesDesignKillFocus(wxFocusEvent& event);
		void OntxtSpecificGrvtyHydroTestKillFocus(wxFocusEvent& event);
		void OntxtSpecificGrvtyStrdPrdKillFocus(wxFocusEvent& event);
		void OntxtDesignTempKillFocus(wxFocusEvent& event);
		void OntxtDesignInternalPressureKillFocus(wxFocusEvent& event);
		void OntxtPressureCmbFactKillFocus(wxFocusEvent& event);
		void OntxtDesignExtPressureKillFocus(wxFocusEvent& event);
		void OntxtExtPressureCmbFactorKillFocus(wxFocusEvent& event);
		void OntxtCourseWidthFirstShellBtmKillFocus(wxFocusEvent& event);
		void OntxtCorrosionAllowanceFirstShllBtmKillFocus(wxFocusEvent& event);
		void OntxtJointEffcncyShellVertSeamsKillFocus(wxFocusEvent& event);
		void OntxtCorrosionAllowanceBtmPlateKillFocus(wxFocusEvent& event);
		void OntxtCorrosionAllowanceFixedRoofKillFocus(wxFocusEvent& event);


		void OntxtPeakGroundAccelKillFocus(wxFocusEvent& event);
		void OntxtASCESpectralAccelShortKillFocus(wxFocusEvent& event);
		void OntxtASCESpectralAccelOneSecKillFocus(wxFocusEvent& event);
		void OntxtTransitionLongGrndKillFocus(wxFocusEvent& event);
		void OntxtCoeffAdjustKillFocus(wxFocusEvent& event);
		void OntxtAccelBaseSiteCoeffKillFocus(wxFocusEvent& event);
		void OntxtVelBasedSiteCoeffKillFocus(wxFocusEvent& event);
		void OntxtRRoofKillFocus(wxFocusEvent& event);
		void OntxtLiveLoadKillFocus(wxFocusEvent& event);
		void OntxtBalancedSLKillFocus(wxFocusEvent& event);
		void OntxtUnBalancedSLKillFocus(wxFocusEvent& event);
		void OntxtMaterialRoofLeftDClick(wxMouseEvent& event);
		void OntxtWeightFloatingRoofKillFocus(wxFocusEvent& event);
		void OntxtDomeRadiusKillFocus(wxFocusEvent& event);
		void OntxtWeightNozzleKillFocus(wxFocusEvent& event);
		void OntxtWeightPlatformKillFocus(wxFocusEvent& event);
		void OntxtSlopeRoofKillFocus(wxFocusEvent& event);
		bool is_fraction1(std::string str);
		void OntxtWtGeodesicRoofKillFocus(wxFocusEvent& event);
		void OntxtCRMaterial1LeftDClick(wxMouseEvent& event);
		void OntxtCRMaterial0LeftDClick(wxMouseEvent& event);
		void OntxtCRMaterial2LeftDClick(wxMouseEvent& event);
		void OntxtCRSize1LeftDClick(wxMouseEvent& event);
		void OntxtCRSize2LeftDClick(wxMouseEvent& event);
   		void OntxtTBarKillFocus(wxFocusEvent& event);
   		void OntxtWBarKillFocus(wxFocusEvent& event);
   		void OntxtLBarKillFocus(wxFocusEvent& event);
   		void OntxtTShellKillFocus(wxFocusEvent& event);
   		void OntxtWShellKillFocus(wxFocusEvent& event);
   		void OntxtSpaceTopWGTopTankKillFocus(wxFocusEvent& event);
		void OntxtMinWidthTopWGAsWalkwayKillFocus(wxFocusEvent& event);
		void OntxtWoWKillFocus(wxFocusEvent& event);
		void OntxtToWKillFocus(wxFocusEvent& event);
		void OntxtHoFKillFocus(wxFocusEvent& event);
		void OntxtToFKillFocus(wxFocusEvent& event);
   		void OntxtNumStiffMaxKillFocus(wxFocusEvent& event);
   		void OntxtDesignWindVelKillFocus(wxFocusEvent& event);
        void OntxtGustDesignWindSpeedKillFocus(wxFocusEvent& event);
        void OntxtVelPressureExpCoeffKillFocus(wxFocusEvent& event);
        void OntxtTopographicFactorKillFocus(wxFocusEvent& event);
        void OntxtDirectionFactorKillFocus(wxFocusEvent& event);
        void OntxtGustFactorKillFocus(wxFocusEvent& event);
        void OntxtPGASpectralAccelShortKillFocus(wxFocusEvent& event);
        void OntxtPGASpectralAccelOneSecKillFocus(wxFocusEvent& event);
        void OntxtVelBaseSiteCoeffKillFocus(wxFocusEvent& event);
		void OntxtRequiredThicknessKillFocus(wxFocusEvent& event);
		void OntxtCorrWeightKillFocus(wxFocusEvent& event);
		void OntxtPercWeightKillFocus(wxFocusEvent& event);
		void OntxtSlopeNumKillFocus(wxFocusEvent& event);
		void OntxtSlopeDenKillFocus(wxFocusEvent& event);

    private:
        InputData *m_inputData;
        bool m_isNewData;
		std::string resultFileName;
		int rowNum;

        void setupInputScreen_1Validators();
        void setInputScreen1InitialControlValues();

        void setInputScreen_1InitialControlStates();

        void setupWindDataValidators();
        void setWindDataInitialControlValues();

        void setWindDataInitialControlStates();

        void setupSeismicDataValidators();
        void setSeismicDataInitialControlValues();

        void setSeismicDataInitialControlStates();

        void setupShellDesignValidators();
        void setShellDesignInitialControlValues();

        void setShellDesignInitialControlStates();

        void setupPrimaryWindGirderDesignValidators();
        void setPrimaryWindGirderDesignInitialControlValues();

        void setPrimaryWindGirderDesignInitialControlStates();

        void setupRoofDataValidators();
        void setRoofDataInitialControlValues();

        void setRoofDataInitialControlStates();

        void setupRoofToShellValidators();
        void setRoofToShellInitialControlValues();

        void setRoofToShellInitialControlStates();

        void setStiffenerElevationInitialControlValues();
        void setStiffenerElevationControlStates(bool label=false);

        void setupStiffenerElevationValidators();

        void setStiffenerSizeInitialControlValues();
        void setStiffenerSizeControlStates(bool label=false);

        void setupStiffenerSizeValidators();


        bool validateEntries();
        bool validateInputScreen_1Entries();
        bool validateWindDataEntries();
        bool validateSeismicDataEntries();
        bool validateRoofDataEntries();
        bool validateRoofToShellEntries();

        bool transferDataFromWindowData();
        bool transferInputScreen_1WindowData();
        bool transferWindDataWindowData();
        bool transferSeismicDataWindowData();
        bool transferRoofDataWindowData();
        bool transferRoofToShellWindowData();

        void inputScreen1Calculations();
        double roundup(double, int);
        void changeVisibleWindDataFields(bool bShow = false);
        void updateCodeWindowLoadSelectionChange();
        void changeActiveNotebookPage(size_t pageID);

        void updateSeismicDesignDataAndControls(int currentDesignCode, bool setDefault = true);
        bool transferSeismicDesignControlsData();

        void changeWalkwayRelatedControlsVisibility(int selection);
        void updatePrimaryWindGirderScreen();

        void updateVisibleFieldsRoofToShellUser(int selection);
        void updateVisibleFieldsRoofToShellUserAD(int selection);
		void updateDesignWindVel();
		void stretchLastCol(wxGrid *myGrid);
		bool validateshelldesignwindow();
		bool validatePwgDataWindow();
		bool validateSeismicWindow();


    public:
        void setResultFileName(std::string fileName)
		{
			resultFileName=fileName.substr(0, fileName.find_last_of(".")-4);
		}
		std::string getResultFileName(){return resultFileName;}

        void SetInputData(InputData *inputData) { m_inputData = inputData; }
        void SetIsNewData(bool isNewData) {m_isNewData = isNewData;}
        InputData *GetInputData() { return m_inputData; }
        void SetupValidators();
        void SetInitialControlValues();
        void SetInitialControlStates();
        void ChangeReadabilityShellDesign(int row, bool readOnly);
		void updateRoofSlope(bool show);
		void updateRoofSlopeValues();
		void setRoofDataDefaultValues();
        wxStaticBitmap* StaticBitmap;
};

#endif
